# Generated by Django 3.2.9 on 2022-05-29 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='top_bidder',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
